### ISSUE TITLE
Latest pdagent incompatible with pdagent-integrations

### ISSUE THREAD

**Issue by mrballcb** [PagerDuty/pdagent-integrations#15]
The current pdagent-integrations (specifically pd-zabbix) passes 8 arguments to the enqueue function.  The latest pdagent (1.4) has an enqueue function that requires 10 arguments.  The prior pdagent (1.3) only required 8 arguments.  Rolling back pdagent to version 1.3 allows the current pd-agent-integrations to work.

The two extra fields are called client_url and client_id (from memory, might be slightly off).  I did not test if I could just pass empty strings.  It was easier to configure chef to roll the pdagent version back to 1.3.

Could we get an update to the integrations apps for the latest pdagent version?  If I knew what was supposed to be in those two versions (point me to a doc explaining them) I would submit a pull request.

**Comment by cncook001** [comment]
Commit in question: https://github.com/PagerDuty/pdagent/commit/56f0f4064bff3319e6e33bc28b8d88cd72caa0ee

**Comment by ryanbsaunders** [comment]
Can confirm this is also an issue with pd-nagios.  We rolled back to 1.3 to fix.

**Comment by lfepp** [comment]
Sorry for the delay in closing this out but this issue was resolved with [this commit](https://github.com/PagerDuty/pdagent-integrations/commit/fa3beafa18e6f5f8a0a46568a958f5e51cd1ddd5) and the integrations should be working with pdagent 1.4. If you're still running into issues with 1.4, please contact [support@pagerduty.com](mailto:support@pagerduty.com) and our team can help you resolve the issue.
